# coding: utf-8

"""
    Power BI Report Server REST API

    The Power BI Report Server REST API provides programmatic access to the report server catalog.  For example, basic CRUD operations can be done on folders, reports, KPIs, data sources, datasets, refresh plans, subscriptions, etc.     The REST API can also be used to provide more advanced functionality, such as: * Navigate the folder hierarchy * Discover the contents of a folder * Download a report definition * Modify default report parameters * Change or execute a refresh plan * A whole lot more  The REST API is a RESTful successor to the legacy [SOAP API](https://msdn.microsoft.com/library/reportservice2010.reportingservice2010.aspx).  Since Power BI Report Server is a superset of SQL Server Reporting Services, the Power BI Report Server REST API is a superset of the  [SQL Server Reporting Services REST API](https://app.swaggerhub.com/apis/microsoft-rs/SSRS/2.0).  __Power BI Report Server API Additions__ * October 2020 Release   * /PowerBIReports({Id})/DataModelParameters(GET & POST)  * January 2019 Release   * /PowerBIReports({Id})/DataModelRoles (GET)   * /PowerBIReports({Id})/DataModelRoleAssignments (GET & PUT)  Happy coding!  __API samples:__ https://github.com/Microsoft/Reporting-Services  __Developer documentation:__ https://powerbi.microsoft.com/documentation/reportserver-developer-handbook-overview/  __Team Blog:__  https://powerbi.microsoft.com/blog/  __Support forums:__  https://community.powerbi.com/t5/Report-Server/bd-p/ReportServer   # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.catalog_items_api import CatalogItemsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCatalogItemsApi(unittest.TestCase):
    """CatalogItemsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.catalog_items_api.CatalogItemsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_catalog_item(self):
        """Test case for add_catalog_item

        Creates a new CatalogItem.  # noqa: E501
        """
        pass

    def test_delete_catalog_item(self):
        """Test case for delete_catalog_item

        Deletes the specified CatalogItem.  # noqa: E501
        """
        pass

    def test_delete_catalog_items(self):
        """Test case for delete_catalog_items

        Deletes the given list of items  # noqa: E501
        """
        pass

    def test_get_catalog_item(self):
        """Test case for get_catalog_item

        Gets a CatalogItem specified by the Id.  # noqa: E501
        """
        pass

    def test_get_catalog_item_content(self):
        """Test case for get_catalog_item_content

        Gets the content of the specified CatalogItem specified by the Id.  # noqa: E501
        """
        pass

    def test_get_catalog_item_policies(self):
        """Test case for get_catalog_item_policies

        Gets ItemPolicies associated with the specified CatalogItem.  # noqa: E501
        """
        pass

    def test_get_catalog_item_properties(self):
        """Test case for get_catalog_item_properties

        Gets the specified Properties for the CatalogItem (takes list of Property names to retrieve the values)  # noqa: E501
        """
        pass

    def test_get_catalog_item_roles(self):
        """Test case for get_catalog_item_roles

        Gets the list of available Roles for the CatalogItem  # noqa: E501
        """
        pass

    def test_get_catalog_items(self):
        """Test case for get_catalog_items

        Gets an array of CatalogItems.  # noqa: E501
        """
        pass

    def test_move_catalog_items(self):
        """Test case for move_catalog_items

        Moves given list of items to target folder.  # noqa: E501
        """
        pass

    def test_set_catalog_item_policies(self):
        """Test case for set_catalog_item_policies

        Replaces ItemPolicies associated with the specified CatalogItem.  # noqa: E501
        """
        pass

    def test_update_catalog_item(self):
        """Test case for update_catalog_item

        Updates the specified CatalogItem using the provided definition.  # noqa: E501
        """
        pass

    def test_update_catalog_item_properties(self):
        """Test case for update_catalog_item_properties

        Updates a CatalogItem's Properties with the list of given properties.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
