# coding: utf-8

# flake8: noqa

"""
    Power BI Report Server REST API

    The Power BI Report Server REST API provides programmatic access to the report server catalog.  For example, basic CRUD operations can be done on folders, reports, KPIs, data sources, datasets, refresh plans, subscriptions, etc.     The REST API can also be used to provide more advanced functionality, such as: * Navigate the folder hierarchy * Discover the contents of a folder * Download a report definition * Modify default report parameters * Change or execute a refresh plan * A whole lot more  The REST API is a RESTful successor to the legacy [SOAP API](https://msdn.microsoft.com/library/reportservice2010.reportingservice2010.aspx).  Since Power BI Report Server is a superset of SQL Server Reporting Services, the Power BI Report Server REST API is a superset of the  [SQL Server Reporting Services REST API](https://app.swaggerhub.com/apis/microsoft-rs/SSRS/2.0).  __Power BI Report Server API Additions__ * October 2020 Release   * /PowerBIReports({Id})/DataModelParameters(GET & POST)  * January 2019 Release   * /PowerBIReports({Id})/DataModelRoles (GET)   * /PowerBIReports({Id})/DataModelRoleAssignments (GET & PUT)  Happy coding!  __API samples:__ https://github.com/Microsoft/Reporting-Services  __Developer documentation:__ https://powerbi.microsoft.com/documentation/reportserver-developer-handbook-overview/  __Team Blog:__  https://powerbi.microsoft.com/blog/  __Support forums:__  https://community.powerbi.com/t5/Report-Server/bd-p/ReportServer   # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.cache_refresh_plans_api import CacheRefreshPlansApi
from swagger_client.api.catalog_items_api import CatalogItemsApi
from swagger_client.api.data_sets_api import DataSetsApi
from swagger_client.api.data_sources_api import DataSourcesApi
from swagger_client.api.excel_workbooks_api import ExcelWorkbooksApi
from swagger_client.api.extensions_api import ExtensionsApi
from swagger_client.api.favorite_items_api import FavoriteItemsApi
from swagger_client.api.folders_api import FoldersApi
from swagger_client.api.kpis_api import KpisApi
from swagger_client.api.linked_reports_api import LinkedReportsApi
from swagger_client.api.me_api import MeApi
from swagger_client.api.mobile_reports_api import MobileReportsApi
from swagger_client.api.power_bi_reports_api import PowerBIReportsApi
from swagger_client.api.reports_api import ReportsApi
from swagger_client.api.resources_api import ResourcesApi
from swagger_client.api.session_api import SessionApi
from swagger_client.api.subscriptions_api import SubscriptionsApi
from swagger_client.api.system_api import SystemApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.allowed_action import AllowedAction
from swagger_client.models.bulk_operations_result import BulkOperationsResult
from swagger_client.models.cache_options import CacheOptions
from swagger_client.models.cache_refresh_plan import CacheRefreshPlan
from swagger_client.models.catalog_item import CatalogItem
from swagger_client.models.catalog_item_type import CatalogItemType
from swagger_client.models.comment import Comment
from swagger_client.models.credentials_stored_in_server import CredentialsStoredInServer
from swagger_client.models.credentials_supplied_by_user import CredentialsSuppliedByUser
from swagger_client.models.daily_recurrence import DailyRecurrence
from swagger_client.models.data_model_data_source import DataModelDataSource
from swagger_client.models.data_model_data_source_auth_type import DataModelDataSourceAuthType
from swagger_client.models.data_model_data_source_kind import DataModelDataSourceKind
from swagger_client.models.data_model_data_source_type import DataModelDataSourceType
from swagger_client.models.data_model_parameter import DataModelParameter
from swagger_client.models.data_model_role import DataModelRole
from swagger_client.models.data_model_role_assignment import DataModelRoleAssignment
from swagger_client.models.data_set import DataSet
from swagger_client.models.data_set_aggregate_value_parameters import DataSetAggregateValueParameters
from swagger_client.models.data_set_columns import DataSetColumns
from swagger_client.models.data_set_data import DataSetData
from swagger_client.models.data_set_data_parameters import DataSetDataParameters
from swagger_client.models.data_set_field import DataSetField
from swagger_client.models.data_set_item import DataSetItem
from swagger_client.models.data_set_parameter import DataSetParameter
from swagger_client.models.data_set_parameter_info import DataSetParameterInfo
from swagger_client.models.data_set_row import DataSetRow
from swagger_client.models.data_set_schema import DataSetSchema
from swagger_client.models.data_source import DataSource
from swagger_client.models.data_source_check_result import DataSourceCheckResult
from swagger_client.models.days_of_week_selector import DaysOfWeekSelector
from swagger_client.models.delete_items_request import DeleteItemsRequest
from swagger_client.models.drillthrough_target import DrillthroughTarget
from swagger_client.models.drillthrough_target_type import DrillthroughTargetType
from swagger_client.models.excel_workbook import ExcelWorkbook
from swagger_client.models.expiration_reference import ExpirationReference
from swagger_client.models.extension import Extension
from swagger_client.models.extension_parameter import ExtensionParameter
from swagger_client.models.extension_settings import ExtensionSettings
from swagger_client.models.extension_type import ExtensionType
from swagger_client.models.favorite_item import FavoriteItem
from swagger_client.models.folder import Folder
from swagger_client.models.history_snapshot import HistorySnapshot
from swagger_client.models.history_snapshot_options import HistorySnapshotOptions
from swagger_client.models.item_execution_type import ItemExecutionType
from swagger_client.models.item_policy import ItemPolicy
from swagger_client.models.kpi import Kpi
from swagger_client.models.kpi_data import KpiData
from swagger_client.models.kpi_data_item import KpiDataItem
from swagger_client.models.kpi_data_item_type import KpiDataItemType
from swagger_client.models.kpi_shared_data_item_aggregation import KpiSharedDataItemAggregation
from swagger_client.models.kpi_value_format import KpiValueFormat
from swagger_client.models.kpi_values import KpiValues
from swagger_client.models.kpi_visualization import KpiVisualization
from swagger_client.models.linked_report import LinkedReport
from swagger_client.models.manifest_item import ManifestItem
from swagger_client.models.minute_recurrence import MinuteRecurrence
from swagger_client.models.mobile_report import MobileReport
from swagger_client.models.mobile_report_manifest import MobileReportManifest
from swagger_client.models.mobile_report_resource_group_type import MobileReportResourceGroupType
from swagger_client.models.mobile_report_thumbnail_type import MobileReportThumbnailType
from swagger_client.models.model_property import ModelProperty
from swagger_client.models.monthly_dow_recurrence import MonthlyDOWRecurrence
from swagger_client.models.monthly_recurrence import MonthlyRecurrence
from swagger_client.models.months_of_year_selector import MonthsOfYearSelector
from swagger_client.models.move_items_request import MoveItemsRequest
from swagger_client.models.o_data_allowed_actions import ODataAllowedActions
from swagger_client.models.o_data_cache_refresh_plans import ODataCacheRefreshPlans
from swagger_client.models.o_data_catalog_items import ODataCatalogItems
from swagger_client.models.o_data_comments import ODataComments
from swagger_client.models.o_data_data_model_parameters import ODataDataModelParameters
from swagger_client.models.o_data_data_model_role_assignments import ODataDataModelRoleAssignments
from swagger_client.models.o_data_data_model_roles import ODataDataModelRoles
from swagger_client.models.o_data_data_set_rows import ODataDataSetRows
from swagger_client.models.o_data_data_sets import ODataDataSets
from swagger_client.models.o_data_data_sources import ODataDataSources
from swagger_client.models.o_data_dependent_items import ODataDependentItems
from swagger_client.models.o_data_excel_workbooks import ODataExcelWorkbooks
from swagger_client.models.o_data_folders import ODataFolders
from swagger_client.models.o_data_kpis import ODataKpis
from swagger_client.models.o_data_linked_reports import ODataLinkedReports
from swagger_client.models.o_data_mobile_report import ODataMobileReport
from swagger_client.models.o_data_power_bi_reports import ODataPowerBIReports
from swagger_client.models.o_data_properties import ODataProperties
from swagger_client.models.o_data_properties1 import ODataProperties1
from swagger_client.models.o_data_query_fields import ODataQueryFields
from swagger_client.models.o_data_report_parameter_definitions import ODataReportParameterDefinitions
from swagger_client.models.o_data_reports import ODataReports
from swagger_client.models.o_data_resources import ODataResources
from swagger_client.models.o_data_subscription_history import ODataSubscriptionHistory
from swagger_client.models.odata_error import OdataError
from swagger_client.models.odata_error_detail import OdataErrorDetail
from swagger_client.models.odata_error_main import OdataErrorMain
from swagger_client.models.parameter_value import ParameterValue
from swagger_client.models.policy import Policy
from swagger_client.models.power_bi_report import PowerBIReport
from swagger_client.models.query import Query
from swagger_client.models.query_fields_request import QueryFieldsRequest
from swagger_client.models.report import Report
from swagger_client.models.report_history_snapshots_options import ReportHistorySnapshotsOptions
from swagger_client.models.report_history_snapshots_options_schedule import ReportHistorySnapshotsOptionsSchedule
from swagger_client.models.report_parameter_definition import ReportParameterDefinition
from swagger_client.models.report_parameter_definition_patch import ReportParameterDefinitionPatch
from swagger_client.models.report_parameter_state import ReportParameterState
from swagger_client.models.report_parameter_type import ReportParameterType
from swagger_client.models.report_parameter_visibility import ReportParameterVisibility
from swagger_client.models.resource import Resource
from swagger_client.models.resource_group import ResourceGroup
from swagger_client.models.resource_item import ResourceItem
from swagger_client.models.role import Role
from swagger_client.models.schedule_definition import ScheduleDefinition
from swagger_client.models.schedule_recurrence import ScheduleRecurrence
from swagger_client.models.schedule_reference import ScheduleReference
from swagger_client.models.shared_data_set_path import SharedDataSetPath
from swagger_client.models.shared_data_sets import SharedDataSets
from swagger_client.models.subscription import Subscription
from swagger_client.models.subscription_history import SubscriptionHistory
from swagger_client.models.system_info import SystemInfo
from swagger_client.models.system_policy import SystemPolicy
from swagger_client.models.thumbnail_item import ThumbnailItem
from swagger_client.models.update_cache_snapshot_result import UpdateCacheSnapshotResult
from swagger_client.models.user import User
from swagger_client.models.user_credentials import UserCredentials
from swagger_client.models.valid_value import ValidValue
from swagger_client.models.week_number_enum import WeekNumberEnum
from swagger_client.models.weekly_recurrence import WeeklyRecurrence
