# coding: utf-8

"""
    Power BI Report Server REST API

    The Power BI Report Server REST API provides programmatic access to the report server catalog.  For example, basic CRUD operations can be done on folders, reports, KPIs, data sources, datasets, refresh plans, subscriptions, etc.     The REST API can also be used to provide more advanced functionality, such as: * Navigate the folder hierarchy * Discover the contents of a folder * Download a report definition * Modify default report parameters * Change or execute a refresh plan * A whole lot more  The REST API is a RESTful successor to the legacy [SOAP API](https://msdn.microsoft.com/library/reportservice2010.reportingservice2010.aspx).  Since Power BI Report Server is a superset of SQL Server Reporting Services, the Power BI Report Server REST API is a superset of the  [SQL Server Reporting Services REST API](https://app.swaggerhub.com/apis/microsoft-rs/SSRS/2.0).  __Power BI Report Server API Additions__ * October 2020 Release   * /PowerBIReports({Id})/DataModelParameters(GET & POST)  * January 2019 Release   * /PowerBIReports({Id})/DataModelRoles (GET)   * /PowerBIReports({Id})/DataModelRoleAssignments (GET & PUT)  Happy coding!  __API samples:__ https://github.com/Microsoft/Reporting-Services  __Developer documentation:__ https://powerbi.microsoft.com/documentation/reportserver-developer-handbook-overview/  __Team Blog:__  https://powerbi.microsoft.com/blog/  __Support forums:__  https://community.powerbi.com/t5/Report-Server/bd-p/ReportServer   # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Extension(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'extension_type': 'ExtensionType',
        'name': 'str',
        'localized_name': 'str',
        'visible': 'bool'
    }

    attribute_map = {
        'extension_type': 'ExtensionType',
        'name': 'Name',
        'localized_name': 'LocalizedName',
        'visible': 'Visible'
    }

    def __init__(self, extension_type=None, name=None, localized_name=None, visible=None, _configuration=None):  # noqa: E501
        """Extension - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._extension_type = None
        self._name = None
        self._localized_name = None
        self._visible = None
        self.discriminator = None

        if extension_type is not None:
            self.extension_type = extension_type
        if name is not None:
            self.name = name
        if localized_name is not None:
            self.localized_name = localized_name
        if visible is not None:
            self.visible = visible

    @property
    def extension_type(self):
        """Gets the extension_type of this Extension.  # noqa: E501


        :return: The extension_type of this Extension.  # noqa: E501
        :rtype: ExtensionType
        """
        return self._extension_type

    @extension_type.setter
    def extension_type(self, extension_type):
        """Sets the extension_type of this Extension.


        :param extension_type: The extension_type of this Extension.  # noqa: E501
        :type: ExtensionType
        """

        self._extension_type = extension_type

    @property
    def name(self):
        """Gets the name of this Extension.  # noqa: E501

        A string value that specifies the name for the Extension. This name will typically be displayed in the user interface.  # noqa: E501

        :return: The name of this Extension.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Extension.

        A string value that specifies the name for the Extension. This name will typically be displayed in the user interface.  # noqa: E501

        :param name: The name of this Extension.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def localized_name(self):
        """Gets the localized_name of this Extension.  # noqa: E501

        A string value that specifies a localized name for the Extension.  # noqa: E501

        :return: The localized_name of this Extension.  # noqa: E501
        :rtype: str
        """
        return self._localized_name

    @localized_name.setter
    def localized_name(self, localized_name):
        """Sets the localized_name of this Extension.

        A string value that specifies a localized name for the Extension.  # noqa: E501

        :param localized_name: The localized_name of this Extension.  # noqa: E501
        :type: str
        """

        self._localized_name = localized_name

    @property
    def visible(self):
        """Gets the visible of this Extension.  # noqa: E501

        A Boolean value that indicates if the Extension is visible. If false, the item will generally not appear in listings of available extensions.  # noqa: E501

        :return: The visible of this Extension.  # noqa: E501
        :rtype: bool
        """
        return self._visible

    @visible.setter
    def visible(self, visible):
        """Sets the visible of this Extension.

        A Boolean value that indicates if the Extension is visible. If false, the item will generally not appear in listings of available extensions.  # noqa: E501

        :param visible: The visible of this Extension.  # noqa: E501
        :type: bool
        """

        self._visible = visible

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Extension, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Extension):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Extension):
            return True

        return self.to_dict() != other.to_dict()
