# coding: utf-8

"""
    Power BI Report Server REST API

    The Power BI Report Server REST API provides programmatic access to the report server catalog.  For example, basic CRUD operations can be done on folders, reports, KPIs, data sources, datasets, refresh plans, subscriptions, etc.     The REST API can also be used to provide more advanced functionality, such as: * Navigate the folder hierarchy * Discover the contents of a folder * Download a report definition * Modify default report parameters * Change or execute a refresh plan * A whole lot more  The REST API is a RESTful successor to the legacy [SOAP API](https://msdn.microsoft.com/library/reportservice2010.reportingservice2010.aspx).  Since Power BI Report Server is a superset of SQL Server Reporting Services, the Power BI Report Server REST API is a superset of the  [SQL Server Reporting Services REST API](https://app.swaggerhub.com/apis/microsoft-rs/SSRS/2.0).  __Power BI Report Server API Additions__ * October 2020 Release   * /PowerBIReports({Id})/DataModelParameters(GET & POST)  * January 2019 Release   * /PowerBIReports({Id})/DataModelRoles (GET)   * /PowerBIReports({Id})/DataModelRoleAssignments (GET & PUT)  Happy coding!  __API samples:__ https://github.com/Microsoft/Reporting-Services  __Developer documentation:__ https://powerbi.microsoft.com/documentation/reportserver-developer-handbook-overview/  __Team Blog:__  https://powerbi.microsoft.com/blog/  __Support forums:__  https://community.powerbi.com/t5/Report-Server/bd-p/ReportServer   # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ScheduleRecurrence(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'minute_recurrence': 'MinuteRecurrence',
        'daily_recurrence': 'DailyRecurrence',
        'weekly_recurrence': 'WeeklyRecurrence',
        'monthly_recurrence': 'MonthlyRecurrence',
        'monthly_dow_recurrence': 'MonthlyDOWRecurrence'
    }

    attribute_map = {
        'minute_recurrence': 'MinuteRecurrence',
        'daily_recurrence': 'DailyRecurrence',
        'weekly_recurrence': 'WeeklyRecurrence',
        'monthly_recurrence': 'MonthlyRecurrence',
        'monthly_dow_recurrence': 'MonthlyDOWRecurrence'
    }

    def __init__(self, minute_recurrence=None, daily_recurrence=None, weekly_recurrence=None, monthly_recurrence=None, monthly_dow_recurrence=None, _configuration=None):  # noqa: E501
        """ScheduleRecurrence - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._minute_recurrence = None
        self._daily_recurrence = None
        self._weekly_recurrence = None
        self._monthly_recurrence = None
        self._monthly_dow_recurrence = None
        self.discriminator = None

        if minute_recurrence is not None:
            self.minute_recurrence = minute_recurrence
        if daily_recurrence is not None:
            self.daily_recurrence = daily_recurrence
        if weekly_recurrence is not None:
            self.weekly_recurrence = weekly_recurrence
        if monthly_recurrence is not None:
            self.monthly_recurrence = monthly_recurrence
        if monthly_dow_recurrence is not None:
            self.monthly_dow_recurrence = monthly_dow_recurrence

    @property
    def minute_recurrence(self):
        """Gets the minute_recurrence of this ScheduleRecurrence.  # noqa: E501


        :return: The minute_recurrence of this ScheduleRecurrence.  # noqa: E501
        :rtype: MinuteRecurrence
        """
        return self._minute_recurrence

    @minute_recurrence.setter
    def minute_recurrence(self, minute_recurrence):
        """Sets the minute_recurrence of this ScheduleRecurrence.


        :param minute_recurrence: The minute_recurrence of this ScheduleRecurrence.  # noqa: E501
        :type: MinuteRecurrence
        """

        self._minute_recurrence = minute_recurrence

    @property
    def daily_recurrence(self):
        """Gets the daily_recurrence of this ScheduleRecurrence.  # noqa: E501


        :return: The daily_recurrence of this ScheduleRecurrence.  # noqa: E501
        :rtype: DailyRecurrence
        """
        return self._daily_recurrence

    @daily_recurrence.setter
    def daily_recurrence(self, daily_recurrence):
        """Sets the daily_recurrence of this ScheduleRecurrence.


        :param daily_recurrence: The daily_recurrence of this ScheduleRecurrence.  # noqa: E501
        :type: DailyRecurrence
        """

        self._daily_recurrence = daily_recurrence

    @property
    def weekly_recurrence(self):
        """Gets the weekly_recurrence of this ScheduleRecurrence.  # noqa: E501


        :return: The weekly_recurrence of this ScheduleRecurrence.  # noqa: E501
        :rtype: WeeklyRecurrence
        """
        return self._weekly_recurrence

    @weekly_recurrence.setter
    def weekly_recurrence(self, weekly_recurrence):
        """Sets the weekly_recurrence of this ScheduleRecurrence.


        :param weekly_recurrence: The weekly_recurrence of this ScheduleRecurrence.  # noqa: E501
        :type: WeeklyRecurrence
        """

        self._weekly_recurrence = weekly_recurrence

    @property
    def monthly_recurrence(self):
        """Gets the monthly_recurrence of this ScheduleRecurrence.  # noqa: E501


        :return: The monthly_recurrence of this ScheduleRecurrence.  # noqa: E501
        :rtype: MonthlyRecurrence
        """
        return self._monthly_recurrence

    @monthly_recurrence.setter
    def monthly_recurrence(self, monthly_recurrence):
        """Sets the monthly_recurrence of this ScheduleRecurrence.


        :param monthly_recurrence: The monthly_recurrence of this ScheduleRecurrence.  # noqa: E501
        :type: MonthlyRecurrence
        """

        self._monthly_recurrence = monthly_recurrence

    @property
    def monthly_dow_recurrence(self):
        """Gets the monthly_dow_recurrence of this ScheduleRecurrence.  # noqa: E501


        :return: The monthly_dow_recurrence of this ScheduleRecurrence.  # noqa: E501
        :rtype: MonthlyDOWRecurrence
        """
        return self._monthly_dow_recurrence

    @monthly_dow_recurrence.setter
    def monthly_dow_recurrence(self, monthly_dow_recurrence):
        """Sets the monthly_dow_recurrence of this ScheduleRecurrence.


        :param monthly_dow_recurrence: The monthly_dow_recurrence of this ScheduleRecurrence.  # noqa: E501
        :type: MonthlyDOWRecurrence
        """

        self._monthly_dow_recurrence = monthly_dow_recurrence

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ScheduleRecurrence, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScheduleRecurrence):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ScheduleRecurrence):
            return True

        return self.to_dict() != other.to_dict()
